version: '3'

services:
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
